version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - bootstrap.memory_lock=true 
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-credentials=true
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 20g  
        reservations:
          memory: 10g  
      restart_policy:
        condition: any
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  esdata1:
    driver: local
