version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
    privileged: true
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  esdata1:
    driver: local

