version: '3'

services:
  semantic-api:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
