version: '1'

services:
  semantic-api:
    build:
      context: .
    ports:
      - "8087:8087"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

    ports:
      - "9200:9200"
