version: '3'

services:
  semantic-api:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    privileged: true
    env_file:
      - .env
    volumes:
      - .:/app
      - ${MAIN_FOLDER}:${MAIN_FOLDER}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
