version: '3'

services:
  semantic-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    privileged: true
    env_file:
      - .env
    volumes:
      - .:/app
      - ${MAIN_FOLDER}:${MAIN_FOLDER}
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '0.5'
        reservations:
          memory: 2G
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
